version: '3.8'
services:
  frontend-react:
    build: ./frontend-react
    ports:
      - "3000:3000"
    depends_on:
      - backend-java
      - backend-python

  backend-java:
    build: ./backend-java
    ports:
      - "8080:8080"
    depends_on:
      - backend-python

  backend-python:
    build: ./backend-python
    ports:
      - "8000:8000"
